# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    _instanceof:
        Syntelix\Common\Domain\Bus\Command\CommandHandler:
            tags: ['internal.command_handler']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Syntelix\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Vessel/Domain/Entity'
            - '../src/Vessel/Application/'
            - '../src/Common/'
            - '../src/Kernel.php'
    Syntelix\Vessel\Infrastructure\API\Controllers\:
        resource: '../src/Vessel/Infrastructure/API/Controllers'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Syntelix\Common\Domain\Bus\Command\CommandBus:
        class: Syntelix\Common\Infrastructure\Bus\Command\InMemoryCommandBus
        arguments: [!tagged internal.command_handler ]